Create table USUARIOS(
IDUSUARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE VARCHAR2(65),
APELLIDOPATERNO VARCHAR2(65),
APELLIDOMATERNO  VARCHAR2(65),
CORREO VARCHAR2(100) NOT NULL UNIQUE,
USERNAME VARCHAR2(100) NOT NULL UNIQUE,
PASSWORD VARCHAR (200) NOT NULL,
ACTIVO NUMBER(1) DEFAULT 1 CHECK (Activo IN(0,1)),
FECHADECREACION TIMESTAMP DEFAULT SYSTIMESTAMP);

CREATE TABLE ROLES(
IDROLES NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE VARCHAR2 (200) NOT NULL UNIQUE
);

ALTER TABLE ROLES
RENAME COLUMN IDROLES TO IDROLE;


CREATE TABLE USUARIOROLES(
IDUSUARIOS NUMBER NOT NULL,
IDROLES NUMBER NOT NULL,
CONSTRAINT PK_USUARIOROLES PRIMARY KEY (IDUSUARIOS,IDROLES),
CONSTRAINT FK_USAURIOroLES_USUARIO FOREIGN KEY (IDUSUARIOS)
REFERENCES USUARIOS(IDUSUARIO) ON DELETE CASCADE,
CONSTRAINT FK_USUARIOROLES_ROL FOREIGN KEY (IDROLES) 
REFERENCES ROLES(IDROLE) ON DELETE CASCADE
);


CREATE TABLE TICKETS(
IDTICKET NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
TITULO VARCHAR2(250) NOT NULL,
DESCRIPCION CLOB,

PRIORIDAD VARCHAR2(20) NOT NULL,
ESTADO VARCHAR2(20) NOT NULL,

CREADOID NUMBER NOT NULL,
ASIGNADOID NUMBER,

  FechaCreacion TIMESTAMP DEFAULT SYSTIMESTAMP,
  FECHAACTUALIZACION TIMESTAMP,

CONSTRAINT FK_TICKECT_CREADOR FOREIGN KEY(CREADOID)
REFERENCES USUARIOS(IDUSUARIO),
CONSTRAINT FK_TICKET_ASIGNADO FOREIGN KEY (ASIGNADOID)
REFERENCES USUARIOS(IDUSUARIO),

CONSTRAINT CHK_TICKET_PRIORIDAD CHECK (PRIORIDAD IN('BAJA','MEDIA','ALTA')),
CONSTRAINT CHK_TICKET_ESTADO CHECK (PRIORIDAD IN('ABIERTO','PROCESO','RESUELTO','CERRADO'))

);

CREATE TABLE Comentarios (
  IDCOMENTARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TicketsId NUMBER NOT NULL,
  AutorId NUMBER NOT NULL,
  Mensaje CLOB NOT NULL,
  FechaCreacion TIMESTAMP DEFAULT SYSTIMESTAMP,

  CONSTRAINT FK_Comentario_Ticket FOREIGN KEY (TicketsId)
    REFERENCES Tickets(IDTICKET) ON DELETE CASCADE,

  CONSTRAINT FK_Comentario_Autor FOREIGN KEY (AutorId)
    REFERENCES Usuarios(idUsuario)
);

INSERT INTO Roles (Nombre) VALUES ('ADMIN');
INSERT INTO Roles (Nombre) VALUES ('USER');
INSERT INTO Roles (Nombre) VALUES ('agente');



INSERT INTO USUARIOS (
  NOMBRE, APELLIDOPATERNO, APELLIDOMATERNO,
  CORREO, USERNAME, PASSWORD
)
VALUES (
  'Gretel', 'Alvarez', 'Ortiz',
  'gretel@test.com', 'gretelDR', '123456'
);


INSERT INTO USUARIOROLES (IDUSUARIOS, IDROLES)
VALUES (3, 2);


Select * from Usuarios;

Select * from roles;

Select * from usuarios;
SELECT constraint_name, search_condition 
FROM user_constraints 
WHERE table_name = 'TICKETS' 
AND constraint_name = 'CHK_TICKET_ESTADO';


ALTER TABLE TICKETS DROP CONSTRAINT CHK_TICKET_ESTADO;


ALTER TABLE TICKETS ADD CONSTRAINT CHK_TICKET_ESTADO 
CHECK (ESTADO IN('ABIERTO','PROCESO','RESUELTO','CERRADO'));



CREATE TABLE NOTIFICACIONES(
notificacionid NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
usuarioid number not null,
tipo varchar2(50),
mensaje varchar2(255) not null,
referenciaid number,
leida number(1) DEFAULT 0 not null,
fechacreacion date default SYSDATE NOT NULL,
FECHALECTURA   TIMESTAMP,

  CONSTRAINT FK_NOTIF_USUARIO  FOREIGN KEY (USUARIOID)  REFERENCES USUARIOS(IDusuario),
    CONSTRAINT CK_NOTIF_TIPO     CHECK (TIPO IN ('TICKET', 'COMENTARIO', 'CAMBIO_ESTADO')),
    CONSTRAINT CK_NOTIF_LEIDA    CHECK (LEIDA IN (0, 1))

);

DROP TABLE notificacion;

COMMENT ON TABLE  NOTIFICACIONES               IS 'Notificaciones del sistema por usuario';
COMMENT ON COLUMN NOTIFICACIONES.TIPO          IS 'TICKET | COMENTARIO | CAMBIO_ESTADO';
COMMENT ON COLUMN NOTIFICACIONES.REFERENCIAID IS 'ID del ticket que originó la notificación';
COMMENT ON COLUMN NOTIFICACIONES.LEIDA         IS '0 = pendiente, 1 = leída';

INSERT INTO NOTIFICACIONES (USUARIOID, TIPO, MENSAJE, REFERENCIAID)
VALUES (1, 'TICKET', 'Se te asignó el Ticket #101', 101);

INSERT INTO NOTIFICACIONES (USUARIOID, TIPO, MENSAJE, REFERENCIAID)
VALUES (1, 'COMENTARIO', 'Nuevo comentario en Ticket #101', 101);

INSERT INTO NOTIFICACIONES (USUARIOID, TIPO, MENSAJE, REFERENCIAID)
VALUES (1, 'CAMBIO_ESTADO', 'Ticket #101 cambió a EN PROCESO', 101);
